#!/usr/bin/env node
/**
 * obsidian-deep.cjs — Obsidian Integration for CCDEW
 * 
 * Phase 4: Obsidian Deep (opțional)
 * - Sync CCDEW data with Obsidian vault
 * - Create knowledge graphs
 * - Generate daily notes
 * - Visualize patterns
 * 
 * Usage:
 *   node obsidian-deep.cjs sync      - Sync with vault
 *   node obsidian-deep.cjs notes     - Generate daily notes
 *   node obsidian-deep.cjs graph      - Generate graph view
 *   node obsidian-deep.cjs search <q> - Search vault
 */

'use strict';

const fs = require('fs');
const path = require('path');

const CCDEW_PATH = '/home/think/CCDEW';
const OBSIDIAN_PATH = '/home/think/OROBS-DATA'; // Your Obsidian vault
const DATA_DIR = path.join(CCDEW_PATH, '.claude-flow/data');

// ── Config ─────────────────────────────────────────────────────────────────
function getConfig() {
  return {
    vault_path: OBSIDIAN_PATH,
    sync_enabled: true,
    daily_notes: true,
    graph_enabled: true,
    auto_sync: false,
    last_sync: null
  };
}

// ── Daily note generation ─────────────────────────────────────────────────
function generateDailyNote() {
  const today = new Date();
  const dateStr = today.toISOString().split('T')[0];
  const dayName = today.toLocaleDateString('ro-RO', { weekday: 'long' });
  const monthName = today.toLocaleDateString('ro-RO', { month: 'long' });
  
  // Load CCDEW stats
  const saflaFile = path.join(DATA_DIR, 'safla.json');
  const circuitFile = path.join(DATA_DIR, 'circuit9.json');
  const learningFile = path.join(DATA_DIR, 'learning.jsonl');
  
  let safla = { nodes: 0, feedbacks: 0, sessions: 0 };
  if (fs.existsSync(saflaFile)) {
    try {
      safla = JSON.parse(fs.readFileSync(saflaFile, 'utf-8'));
    } catch(e) {}
  }
  
  let circuit = { active: false, total_routes: 0 };
  if (fs.existsSync(circuitFile)) {
    try {
      const d = JSON.parse(fs.readFileSync(circuitFile, 'utf-8'));
      circuit = { active: d.active, total_routes: d.total_routes || 0 };
    } catch(e) {}
  }
  
  let learning = 0;
  if (fs.existsSync(learningFile)) {
    learning = fs.readFileSync(learningFile, 'utf-8').trim().split('\n').filter(l => l.trim()).length;
  }
  
  // Generate note content
  const note = `# ${dayName}, ${today.getDate()} ${monthName} ${today.getFullYear()}

> CCDEW Daily Notes — Generated ${new Date().toLocaleString('ro-RO')}

## System Status

| Metric | Value |
|--------|-------|
| SAFLA Nodes | ${safla.nodes || 0} |
| SAFLA Feedbacks | ${safla.feedbacks || 0} |
| SAFLA Sessions | ${safla.sessions || 0} |
| Circuit 9 Active | ${circuit.active ? 'YES' : 'NO'} |
| Circuit 9 Routes | ${circuit.total_routes} |
| Workflow Learning | ${learning} |

## Components

- [x] Enneagram (9-node routing)
- [x] SSA Layer (5D scoring)
- [x] SAFLA (Adaptive feedback)
- [x] CodeBurn (Cost tracking)
- [x] Ruflo (MCP swarm)
- [x] Workflow (Hybrid templates)

## Growth Metrics

\`\`\`
SAFLA Efficiency: ~40%
SSA Target: <25%
Circuit 9: ${circuit.active ? 'Active' : 'Inactive'}
\`\`\`

## Notes

<!-- Add your notes here -->

---

*Auto-generated by CCDEW Obsidian Integration*
`;
  
  return { dateStr, note };
}

function writeDailyNote() {
  const config = getConfig();
  if (!fs.existsSync(config.vault_path)) {
    console.log(`⚠️  Obsidian vault not found: ${config.vault_path}`);
    console.log('   Set OBSIDIAN_PATH or create vault at:', config.vault_path);
    return null;
  }
  
  const { dateStr, note } = generateDailyNote();
  
  // Create daily notes folder
  const dailyDir = path.join(config.vault_path, 'Daily');
  if (!fs.existsSync(dailyDir)) fs.mkdirSync(dailyDir, { recursive: true });
  
  const filePath = path.join(dailyDir, `${dateStr}.md`);
  fs.writeFileSync(filePath, note);
  
  console.log(`✅ Daily note created: ${filePath}`);
  return filePath;
}

// ── Graph visualization ─────────────────────────────────────────────────────
function generateGraph() {
  const saflaFile = path.join(DATA_DIR, 'safla.json');
  const circuitFile = path.join(DATA_DIR, 'circuit9.json');
  
  let nodes = [];
  let edges = [];
  
  // Load SAFLA nodes
  if (fs.existsSync(saflaFile)) {
    try {
      const safla = JSON.parse(fs.readFileSync(saflaFile, 'utf-8'));
      for (const [name, data] of Object.entries(safla.nodes || {})) {
        nodes.push({
          id: name,
          type: 'safla_node',
          weight: data.weight || 1.0,
          feedbacks: data.feedbacks || 0
        });
      }
    } catch(e) {}
  }
  
  // Load circuit edges
  if (fs.existsSync(circuitFile)) {
    try {
      const circuit = JSON.parse(fs.readFileSync(circuitFile, 'utf-8'));
      for (const [arc, weight] of Object.entries(circuit.arc_weights || {})) {
        const [from, to] = arc.split('→');
        edges.push({
          from: from.trim(),
          to: to.trim(),
          weight: weight
        });
        // Add nodes if not exist
        if (!nodes.find(n => n.id === from.trim())) {
          nodes.push({ id: from.trim(), type: 'circuit_node' });
        }
        if (!nodes.find(n => n.id === to.trim())) {
          nodes.push({ id: to.trim(), type: 'circuit_node' });
        }
      }
    } catch(e) {}
  }
  
  // Generate Mermaid graph
  const mermaid = `# CCDEW Knowledge Graph

\`\`\`mermaid
graph TD
    subgraph SAFLA
${nodes.filter(n => n.type === 'safla_node').map(n => `        ${n.id}[${n.id}]`).join('\n')}
    end
    
    subgraph Circuit9
${nodes.filter(n => n.type === 'circuit_node').map(n => `        ${n.id}((${n.id}))`).join('\n')}
    end
    
${edges.map(e => `    ${e.from} -->|${e.weight}| ${e.to}`).join('\n')}
\`\`\`

## Stats

- **Nodes:** ${nodes.length}
- **Edges:** ${edges.length}
- **SAFLA Nodes:** ${nodes.filter(n => n.type === 'safla_node').length}
- **Circuit Nodes:** ${nodes.filter(n => n.type === 'circuit_node').length}
`;
  
  return { nodes, edges, mermaid };
}

function writeGraph() {
  const config = getConfig();
  if (!fs.existsSync(config.vault_path)) {
    console.log(`⚠️  Obsidian vault not found: ${config.vault_path}`);
    return null;
  }
  
  const { nodes, edges, mermaid } = generateGraph();
  
  const graphDir = path.join(config.vault_path, 'CCDEW');
  if (!fs.existsSync(graphDir)) fs.mkdirSync(graphDir, { recursive: true });
  
  const filePath = path.join(graphDir, 'knowledge-graph.md');
  fs.writeFileSync(filePath, mermaid);
  
  console.log(`✅ Graph generated: ${filePath}`);
  console.log(`   Nodes: ${nodes.length}, Edges: ${edges.length}`);
  return filePath;
}

// ── Sync CCDEW data ─────────────────────────────────────────────────────────
function syncData() {
  const config = getConfig();
  if (!fs.existsSync(config.vault_path)) {
    console.log(`⚠️  Obsidian vault not found: ${config.vault_path}`);
    return;
  }
  
  console.log('🔄 Syncing CCDEW data with Obsidian vault...');
  
  // Sync daily notes
  if (config.daily_notes) {
    writeDailyNote();
  }
  
  // Sync graph
  if (config.graph_enabled) {
    writeGraph();
  }
  
  // Sync SAFLA data
  const saflaFile = path.join(DATA_DIR, 'safla.json');
  if (fs.existsSync(saflaFile)) {
    const saflaDir = path.join(config.vault_path, 'CCDEW/Safla');
    if (!fs.existsSync(saflaDir)) fs.mkdirSync(saflaDir, { recursive: true });
    
    const dest = path.join(saflaDir, 'safla-data.md');
    const safla = JSON.parse(fs.readFileSync(saflaFile, 'utf-8'));
    
    const md = `# SAFLA Data

> Last updated: ${new Date().toLocaleString('ro-RO')}

## Overview

| Metric | Value |
|--------|-------|
| Total Nodes | ${Object.keys(safla.nodes || {}).length} |
| Total Feedbacks | ${safla.total_feedbacks || 0} |
| Sessions | ${safla.sessions || 0} |

## Nodes

${Object.entries(safla.nodes || {}).map(([name, data]) => 
`| ${name} | Weight: ${data.weight || 1.0} | Feedbacks: ${data.feedbacks || 0} |`
).join('\n')}

| Name | Weight | Feedbacks |
|------|--------|-----------|
${Object.entries(safla.nodes || {}).map(([name, data]) => 
`| ${name} | ${(data.weight || 1.0).toFixed(2)} | ${data.feedbacks || 0} |`
).join('\n')}
`;
    
    fs.writeFileSync(dest, md);
    console.log(`   ✅ SAFLA data synced: ${dest}`);
  }
  
  console.log('✅ Sync complete!');
}

// ── Search vault ───────────────────────────────────────────────────────────
function searchVault(query) {
  const config = getConfig();
  if (!fs.existsSync(config.vault_path)) {
    console.log(`⚠️  Obsidian vault not found: ${config.vault_path}`);
    return [];
  }
  
  console.log(`🔍 Searching vault for: "${query}"`);
  
  const results = [];
  
  function searchDir(dir) {
    if (!fs.existsSync(dir)) return;
    
    const files = fs.readdirSync(dir);
    for (const file of files) {
      const full = path.join(dir, file);
      const stat = fs.statSync(full);
      
      if (stat.isDirectory() && !file.startsWith('.')) {
        searchDir(full);
      } else if (file.endsWith('.md')) {
        const content = fs.readFileSync(full, 'utf-8');
        if (content.toLowerCase().includes(query.toLowerCase())) {
          results.push({
            file: full.replace(config.vault_path, ''),
            name: file
          });
        }
      }
    }
  }
  
  searchDir(config.vault_path);
  
  console.log(`   Found ${results.length} results:`);
  for (const r of results.slice(0, 10)) {
    console.log(`   - ${r.file}`);
  }
  
  return results;
}

// ── CLI Interface ──────────────────────────────────────────────────────────
function main() {
  const args = process.argv.slice(2);
  
  if (!args.length) {
    console.log('Usage:');
    console.log('  node obsidian-deep.cjs sync      - Sync with vault');
    console.log('  node obsidian-deep.cjs daily      - Generate daily note');
    console.log('  node obsidian-deep.cjs graph      - Generate graph view');
    console.log('  node obsidian-deep.cjs search <q> - Search vault');
    console.log('  node obsidian-deep.cjs safla      - Sync SAFLA data');
    console.log('');
    console.log('Config:');
    console.log('  Vault path:', getConfig().vault_path);
    process.exit(1);
  }
  
  const cmd = args[0];
  
  switch(cmd) {
    case 'sync':
      syncData();
      break;
      
    case 'daily':
      writeDailyNote();
      break;
      
    case 'graph':
      writeGraph();
      break;
      
    case 'search':
      if (args.length < 2) {
        console.log('❌ Usage: obsidian-deep.cjs search <query>');
        process.exit(1);
      }
      searchVault(args.slice(1).join(' '));
      break;
      
    case 'safla':
      const saflaFile = path.join(DATA_DIR, 'safla.json');
      if (fs.existsSync(saflaFile)) {
        console.log('📊 SAFLA Data:\n');
        const safla = JSON.parse(fs.readFileSync(saflaFile, 'utf-8'));
        console.log(JSON.stringify(safla, null, 2));
      }
      break;
      
    default:
      console.log('❌ Unknown command:', cmd);
      process.exit(1);
  }
}

if (require.main === module) {
  main();
}

module.exports = { syncData, generateDailyNote, generateGraph, searchVault };