#!/usr/bin/env node
/**
 * obsidian-deep.cjs — Obsidian Integration (SLIM)
 * Usage: node obsidian-deep.cjs [sync|daily|graph|search <q>]
 */
'use strict';
const fs = require('fs'), path = require('path');
const CCDEW_PATH = '/home/think/CCDEW';
const OBS_PATH = '/home/think/OROBS-DATA';
const DATA_DIR = path.join(CCDEW_PATH, '.claude-flow/data');

function sync() {
  if (!fs.existsSync(OBS_PATH)) { console.log('Vault not found: ' + OBS_PATH); return; }
  // Daily note
  const today = new Date(), dateStr = today.toISOString().split('T')[0];
  const safla = path.join(DATA_DIR, 'safla.json');
  let nodes = 0, feedbacks = 0;
  try { const d = JSON.parse(fs.readFileSync(safla, 'utf-8')); nodes = Object.keys(d.nodes || {}).length; feedbacks = d.total_feedbacks || 0; } catch {}
  const note = '# ' + today.toLocaleDateString('ro-RO') + '\n\n## System\n|Metric|Value|\n|------|-----|\n|SAFLA Nodes|' + nodes + '|\n|SAFLA Feedbacks|' + feedbacks + '|\n\n---\n*Generated by CCDEW*\n';
  const dailyDir = path.join(OBS_PATH, 'Daily');
  if (!fs.existsSync(dailyDir)) fs.mkdirSync(dailyDir, { recursive: true });
  fs.writeFileSync(path.join(dailyDir, dateStr + '.md'), note);
  console.log('Daily note: ' + dateStr + '.md');
  
  // Graph
  const graphDir = path.join(OBS_PATH, 'CCDEW');
  if (!fs.existsSync(graphDir)) fs.mkdirSync(graphDir, { recursive: true });
  const circuit = path.join(DATA_DIR, 'circuit9.json');
  let arcs = 0, nodes_c = 0;
  try { const c = JSON.parse(fs.readFileSync(circuit, 'utf-8')); arcs = Object.keys(c.arc_weights || {}).length; nodes_c = c.current_circuit?.length || 0; } catch {}
  const graph = '# CCDEW Graph\n\n## Circuit 9\n- Nodes: ' + nodes_c + '\n- Arcs: ' + arcs + '\n\n```mermaid\ngraph TD\n  1(1) --> 2(2)\n  2 --> 3(3)\n```\n';
  fs.writeFileSync(path.join(graphDir, 'graph.md'), graph);
  console.log('Graph: graph.md');
  console.log('Sync complete!');
}

function search(query) {
  if (!fs.existsSync(OBS_PATH)) { console.log('Vault not found'); return; }
  const results = [];
  function scan(dir) {
    if (!fs.existsSync(dir)) return;
    for (const f of fs.readdirSync(dir)) {
      const full = path.join(dir, f);
      if (fs.statSync(full).isDirectory() && !f.startsWith('.')) scan(full);
      else if (f.endsWith('.md')) {
        const content = fs.readFileSync(full, 'utf-8');
        if (content.toLowerCase().includes(query.toLowerCase())) results.push(full.replace(OBS_PATH, ''));
      }
    }
  }
  scan(OBS_PATH);
  console.log('Found ' + results.length + ' results:');
  results.slice(0, 10).forEach(r => console.log('  ' + r));
}

function main() {
  const args = process.argv.slice(2), cmd = args[0];
  if (!cmd) { console.log('sync|daily|graph|search <q>'); return; }
  if (cmd === 'sync') sync();
  else if (cmd === 'daily') { const d = new Date(); console.log(d.toLocaleDateString('ro-RO')); }
  else if (cmd === 'graph') console.log('Use: sync');
  else if (cmd === 'search') search(args.slice(1).join(' '));
  else console.log('Unknown: ' + cmd);
}

if (require.main === module) main();
module.exports = { sync, search };